name: GOAT Compile

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3

      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target

  sca:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project with Maven
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Compilacion"
        run: ./mvnw clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports' 

      - name: Upload Test results
        uses: actions/upload-artifact@main
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      - name: "Revision del reporte"
        run: ls -ltra ${{github.workspace}}/reports
      - name: "Imagen Docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test
          docker images
      - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml

      - name: "Correrse en el contenedor"
        run: docker run -d webgoat/test
      - name: "Iniciar el contenedor"
        run: docker run -d -p 8080:8080 --name michiote webgoat/test
      - name: "Listar"
        run: docker ps -a      


  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Revisar código
      uses: actions/checkout@v3
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
        horusec start -p="./" -e="false"
